name: 最终构建APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: 设置Android SDK (简化版)
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH
        echo "/usr/local/lib/android/sdk/tools" >> $GITHUB_PATH
        
    - name: 安装Gradle 8.2
      run: |
        wget -q https://services.gradle.org/distributions/gradle-8.2-bin.zip
        unzip -q gradle-8.2-bin.zip
        echo "$PWD/gradle-8.2/bin" >> $GITHUB_PATH
        
    - name: 创建local.properties
      run: echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
      
    - name: 验证环境
      run: |
        echo "Java版本:"
        java -version
        echo "Gradle版本:"
        gradle --version
        echo "Android SDK路径:"
        ls -la /usr/local/lib/android/sdk/ || echo "SDK路径不存在"
        
    - name: 清理项目
      run: gradle clean --no-daemon
      
    - name: 构建Debug APK
      run: gradle assembleDebug --no-daemon --stacktrace
      
    - name: 检查APK文件
      run: |
        echo "查找APK文件:"
        find . -name "*.apk" -type f
        echo "检查输出目录:"
        ls -la app/build/outputs/apk/debug/ || echo "debug目录不存在"
        
    - name: 上传APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: 录音转文字-最终版
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30 