name: 简化构建APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: 设置Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        build-tools: 30.0.3
        
    - name: 创建local.properties
      run: echo "sdk.dir=$ANDROID_HOME" > local.properties
      
    - name: 设置权限
      run: chmod +x gradlew
      
    - name: 清理项目
      run: ./gradlew clean --no-daemon
      
    - name: 构建Debug APK
      run: ./gradlew assembleDebug --no-daemon --stacktrace --no-parallel
      
    - name: 上传APK
      uses: actions/upload-artifact@v4
      with:
        name: 录音转文字-简化版
        path: app/build/outputs/apk/debug/*.apk
        retention-days: 30 